export const coffeeProductList = [
  {
    id: 118836,
    name: "Espresso Milano Style",
    country: "Colombia",
    type: "Arabica",
    price: 339,
    currency: "CZK",
    sale: false,
  },
  {
    id: 118834336,
    name: "Espresso Intense",
    country: "Colombia",
    type: "Arabica",
    price: 689,
    currency: "CZK",
    sale: false,
  },
  {
    id: 11882334336,
    name: "Espresso Milano ",
    country: "Colombia",
    type: "Arabica",
    price: 689,
    currency: "CZK",
    sale: false,
  },
  {
    id: 11883436,
    name: "Espresso Chocolate",
    country: "Colombia",
    type: "Arabica",
    price: 1099,
    currency: "CZK",
    sale: false,
  },
  {
    id: 9918831123436,
    name: "Caffe Chocolate",
    country: "Porto Rico",
    type: "Arabica",
    price: 679,
    currency: "CZK",
    sale: false,
  },
  {
    id: 991883436,
    name: "Caffe Chocolate",
    country: "Porto Rico",
    type: "Arabica",
    price: 579,
    currency: "CZK",
    sale: false,
  },
  {
    id: 118833236,
    name: "Espresso Iced Style",
    country: "Brazil",
    type: "Arabica",
    price: 539,
    currency: "CZK",
    sale: false,
  },
  {
    id: 118839,
    name: "Caffè Crema Intense",
    country: "Brazil",
    type: "Arabica",
    price: 629,
    currency: "CZK",
    sale: true,
  },
  {
    id: 11883246,
    name: "Espresso Sicilia Style",
    country: "Brazil",
    type: "Robusta & Arabica",
    price: 729,
    currency: "CZK",
    sale: false,
  },
  {
    id: 11884536,
    name: "Espresso Dark",
    country: "Costa Rica",
    type: "Robusta & Arabica",
    price: 629,
    type: "Arabica",
    price: 899,
    currency: "CZK",
    sale: false,
  },
  {
    id: 11885436,
    name: "Caffè Intense",
    country: "Vietnam",
    type: "Robusta",
    price: 299,
    currency: "CZK",
    sale: false,
  },
  {
    id: 11885324436,
    name: "Caffè Italiano",
    country: "Indonesia",
    type: "Robusta",
    price: 199,
    currency: "CZK",
    sale: true,
  },
  {
    id: 11885344363,
    name: "Caffè Ital",
    country: "Vietnam",
    type: "Robusta",
    price: 15,
    currency: "USD",
    sale: true,
  },

  {
    id: 118223836,
    name: "Espresso Milano Style",
    country: "Colombia",
    type: "Arabica",
    price: 32,
    currency: "USD",
    sale: false,
  },
  {
    id: 1182323834336,
    name: "Espresso Intense",
    country: "Colombia",
    type: "Arabica",
    price: 21,
    currency: "USD",
    sale: false,
  },
  {
    id: 1188232323234336,
    name: "Espresso Milano ",
    country: "Colombia",
    type: "Arabica",
    price: 31,
    currency: "USD",
    sale: false,
  },
  {
    id: 33444444444444,
    name: "Espresso Chocolate",
    country: "Colombia",
    type: "Arabica",
    price: 10,
    currency: "USD",
    sale: false,
  },
  {
    id: 991883112323436,
    name: "Caffe Chocolate",
    country: "Porto Rico",
    type: "Arabica",
    price: 67,
    currency: "USD",
    sale: false,
  },
  {
    id: 991843383436,
    name: "Caffe Chocolate",
    country: "Porto Rico",
    type: "Arabica",
    price: 59,
    currency: "USD",
    sale: false,
  },
  {
    id: 1183344833236,
    name: "Espresso Iced Style",
    country: "Brazil",
    type: "Arabica",
    price: 53,
    currency: "USD",
    sale: false,
  },
  {
    id: 1188433339,
    name: "Caffè Crema Intense",
    country: "Brazil",
    type: "Arabica",
    price: 62,
    currency: "USD",
    sale: true,
  },
  {
    id: 118344383246,
    name: "Espresso Sicilia Style",
    country: "Brazil",
    type: "Robusta & Arabica",
    price: 72,
    currency: "USD",
    sale: false,
  },
  {
    id: 118834334536,
    name: "Espresso Dark",
    country: "Costa Rica",
    type: "Robusta & Arabica",
    price: 629,
    type: "Arabica",
    price: 89,
    currency: "USD",
    sale: false,
  },
  {
    id: 118344385436,
    name: "Caffè Intense",
    country: "Vietnam",
    type: "Robusta",
    price: 18,
    currency: "USD",
    sale: false,
  },
  {
    id: 118833445324436,
    name: "Caffè Italiano",
    country: "Indonesia",
    type: "Robusta",
    price: 24,
    currency: "USD",
    sale: true,
  },
];
